### ISSUE TITLE
Running jobs show as running for 51+ years

### ISSUE THREAD

**Issue by Andy-medidata** [RoadieHQ/backstage-plugin-travis-ci#75]
The Date field seems to be showing right for completed builds (passed or failed) but when they're in the `started` Status, they show as having started `over 51 years ago sec`

## Expected Behavior

That the Date field would show the running time of the build

## Current Behavior

it shows `over 51 years ago sec`
![Travis 51 years](https://user-images.githubusercontent.com/44985584/124680868-2439a280-de7c-11eb-9696-bbae350139b6.png)

## Possible Solution

not dug into the code yet

## Steps to Reproduce

It happens to me on every build that's currently running, and corrects once the build is finished.

## Context

We're currently evaluating Backstage, so no direct impact, but have concerns about how it will be perceived by my teams.

## Your Environment

- Plugin Version (version of this software e.g. v0.4.3): 1.0.4
- Backstage version (e.g. 0.1.1-alpha23): 0.7.13
- NodeJS Version (e.g. v12): 14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): OSX 10.15.7
- Browser Information (e.g. chrome 85): Chrome 91.0.4472.114

**Comment by Irma12** [comment]
Thank you for letting us know about this, we will do our best to resolve it as soon as possible @Andy-medidata

**Comment by Irma12** [comment]
@Andy-medidata The issue has been fixed in v1.0.5 :)
